// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mk8.identity.Infrastructure.Contexts;

#nullable disable

namespace mk8.identity.Infrastructure.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.ContributionDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ContributionPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ContributionPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmittedByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ValidatedByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByMembershipId");

                    b.HasIndex("ValidatedByMembershipId");

                    b.HasIndex("MembershipId", "Month", "Year", "Type");

                    b.ToTable("Contributions");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.MatrixAccountDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DisabledByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PrivilegesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("CreatedByMembershipId");

                    b.HasIndex("DisabledByMembershipId");

                    b.HasIndex("PrivilegesId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("MatrixAccounts");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.MessageDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedMatrixAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("DesiredMatrixUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HandledByMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemporaryPassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedMatrixAccountId");

                    b.HasIndex("HandledByMembershipId");

                    b.HasIndex("SenderMembershipId");

                    b.HasIndex("Type", "Status");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.NotificationDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActionCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedToMembershipId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GracePeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int?>("GracePeriodMonthsRemaining")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActionCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActionRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("MinimumRoleRequired")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToMembershipId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RelatedMembershipId");

                    b.HasIndex("MinimumRoleRequired", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.PrivilegesDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("VotingRights")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .IsUnique();

                    b.ToTable("Privileges");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("ActivationDates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("DeactivationDates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GracePeriodMonthsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("GracePeriodMonthsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("GracePeriodStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInGracePeriod")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.ContributionDB", b =>
                {
                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "Membership")
                        .WithMany("Contributions")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "ValidatedBy")
                        .WithMany()
                        .HasForeignKey("ValidatedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Membership");

                    b.Navigation("SubmittedBy");

                    b.Navigation("ValidatedBy");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.MatrixAccountDB", b =>
                {
                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "DisabledBy")
                        .WithMany()
                        .HasForeignKey("DisabledByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("mk8.identity.Infrastructure.Models.Application.PrivilegesDB", "Privileges")
                        .WithMany("MatrixAccounts")
                        .HasForeignKey("PrivilegesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DisabledBy");

                    b.Navigation("Privileges");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.MessageDB", b =>
                {
                    b.HasOne("mk8.identity.Infrastructure.Models.Application.MatrixAccountDB", "CreatedMatrixAccount")
                        .WithMany()
                        .HasForeignKey("CreatedMatrixAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "HandledBy")
                        .WithMany()
                        .HasForeignKey("HandledByMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedMatrixAccount");

                    b.Navigation("HandledBy");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.NotificationDB", b =>
                {
                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "RelatedMembership")
                        .WithMany()
                        .HasForeignKey("RelatedMembershipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedTo");

                    b.Navigation("RelatedMembership");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.PrivilegesDB", b =>
                {
                    b.HasOne("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", "Membership")
                        .WithOne("Privileges")
                        .HasForeignKey("mk8.identity.Infrastructure.Models.Application.PrivilegesDB", "MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.PrivilegesDB", b =>
                {
                    b.Navigation("MatrixAccounts");
                });

            modelBuilder.Entity("mk8.identity.Infrastructure.Models.Application.UserMembershipDB", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Messages");

                    b.Navigation("Privileges");
                });
#pragma warning restore 612, 618
        }
    }
}
